export interface DirectoryMerchant {
  name: string
  provider: string
  category: string
  group: string
  offer: string
  price: number
  unit: string
  distance: number
  badge: string
  image: string
  openNow: boolean
  weekend: boolean
  promotion: boolean
  freeTrial: boolean
  isNew: boolean
  likes: number
}

export const directoryGroups = [
  "All",
  "Coaching",
  "Education",
  "Pet care",
  "Beauty & wellness",
  "Health",
] as const

export type DirectoryGroup = (typeof directoryGroups)[number]

export const directoryGroupTitles: Record<string, string> = {
  All: "All services",
  Coaching: "Coaching & sports",
  Education: "Education",
  "Pet care": "Pet care",
  "Beauty & wellness": "Beauty & wellness",
  Health: "Health",
}

export const sectionGroupLookup: Record<string, string> = {
  "Coaching & sports": "Coaching",
  Coaching: "Coaching",
  Education: "Education",
  "Pet care": "Pet care",
  "Beauty & wellness": "Beauty & wellness",
  Beauty: "Beauty & wellness",
  Health: "Health",
  "Popular merchants": "All",
}

export const directoryMerchants: DirectoryMerchant[] = [
  {
    name: "AquaKids Swimming",
    provider: "AquaKids Academy",
    category: "Swimming lessons",
    group: "Coaching",
    offer: "Trial available",
    price: 45,
    unit: "session",
    distance: 1.2,
    badge: "Featured",
    image:
      "https://images.unsplash.com/photo-1562271613-c3a4be2cc883?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: false,
    freeTrial: true,
    isNew: false,
    likes: 482,
  },
  {
    name: "The Yoga Room",
    provider: "The Yoga Room",
    category: "Yoga classes",
    group: "Coaching",
    offer: "Small groups",
    price: 25,
    unit: "class",
    distance: 2.1,
    badge: "15% OFF",
    image:
      "https://images.unsplash.com/photo-1593811167565-4672e6c8ce4c?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: true,
    freeTrial: false,
    isNew: false,
    likes: 321,
  },
  {
    name: "Baseline Tennis Club",
    provider: "Baseline Tennis Academy",
    category: "Tennis coaching",
    group: "Coaching",
    offer: "Weekend groups",
    price: 38,
    unit: "class",
    distance: 2.4,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: false,
    weekend: true,
    promotion: false,
    freeTrial: false,
    isNew: true,
    likes: 194,
  },
  {
    name: "Peak Performance PT",
    provider: "Peak Performance Studio",
    category: "Personal training",
    group: "Coaching",
    offer: "3-session pack",
    price: 55,
    unit: "session",
    distance: 1.6,
    badge: "Starter pack",
    image:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: false,
    promotion: false,
    freeTrial: true,
    isNew: false,
    likes: 268,
  },
  {
    name: "HoopLab Academy",
    provider: "HoopLab Sports Academy",
    category: "Youth basketball",
    group: "Coaching",
    offer: "Weekday slots",
    price: 30,
    unit: "class",
    distance: 1.9,
    badge: "10% OFF",
    image:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: false,
    weekend: true,
    promotion: true,
    freeTrial: false,
    isNew: false,
    likes: 226,
  },
  {
    name: "Kickoff Football School",
    provider: "Kickoff Football Academy",
    category: "Junior soccer",
    group: "Coaching",
    offer: "New term",
    price: 32,
    unit: "class",
    distance: 2.8,
    badge: "New term",
    image:
      "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: false,
    freeTrial: true,
    isNew: true,
    likes: 207,
  },
  {
    name: "BrightMinds Tutoring",
    provider: "BrightMinds Academy",
    category: "Math & science",
    group: "Education",
    offer: "Small groups",
    price: 55,
    unit: "lesson",
    distance: 0.8,
    badge: "$80 OFF",
    image:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: false,
    promotion: true,
    freeTrial: false,
    isNew: false,
    likes: 280,
  },
  {
    name: "Little Scholars School",
    provider: "Little Scholars Preschool",
    category: "Early learning",
    group: "Education",
    offer: "Open house Sat",
    price: 48,
    unit: "lesson",
    distance: 1.5,
    badge: "Open house",
    image:
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: false,
    weekend: true,
    promotion: false,
    freeTrial: true,
    isNew: true,
    likes: 264,
  },
  {
    name: "Maths Mastery",
    provider: "Maths Mastery Centre",
    category: "Math tuition",
    group: "Education",
    offer: "Free assessment",
    price: 60,
    unit: "lesson",
    distance: 2.0,
    badge: "Assessment",
    image:
      "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: false,
    promotion: false,
    freeTrial: true,
    isNew: false,
    likes: 245,
  },
  {
    name: "CodeCraft Junior Lab",
    provider: "CodeCraft Learning Studio",
    category: "Coding & robotics",
    group: "Education",
    offer: "Weekend lab",
    price: 42,
    unit: "class",
    distance: 2.0,
    badge: "Weekend lab",
    image:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: false,
    freeTrial: false,
    isNew: false,
    likes: 312,
  },
  {
    name: "Little Steps Music",
    provider: "Little Steps Music Studio",
    category: "Early music",
    group: "Education",
    offer: "Trial class",
    price: 35,
    unit: "class",
    distance: 1.7,
    badge: "Trial class",
    image:
      "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: false,
    weekend: true,
    promotion: false,
    freeTrial: true,
    isNew: true,
    likes: 241,
  },
  {
    name: "Paws & Bubbles",
    provider: "Paws & Bubbles Grooming",
    category: "Dog & cat grooming",
    group: "Pet care",
    offer: "15% off first groom",
    price: 48,
    unit: "visit",
    distance: 1.1,
    badge: "15% OFF",
    image:
      "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: true,
    freeTrial: false,
    isNew: false,
    likes: 349,
  },
  {
    name: "The Cat Parlour",
    provider: "The Cat Parlour Grooming",
    category: "Cat grooming",
    group: "Pet care",
    offer: "Gentle care",
    price: 52,
    unit: "visit",
    distance: 2.2,
    badge: "Cat care",
    image:
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: false,
    weekend: false,
    promotion: false,
    freeTrial: false,
    isNew: false,
    likes: 284,
  },
  {
    name: "Wag & Go Mobile Grooming",
    provider: "Mobile grooming van",
    category: "Mobile grooming",
    group: "Pet care",
    offer: "Doorstep service",
    price: 60,
    unit: "visit",
    distance: 1.7,
    badge: "Doorstep",
    image:
      "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: false,
    freeTrial: false,
    isNew: false,
    likes: 327,
  },
  {
    name: "Happy Tails Veterinary",
    provider: "Happy Tails Pet Clinic",
    category: "Pet wellness",
    group: "Pet care",
    offer: "Health check",
    price: 65,
    unit: "visit",
    distance: 2.6,
    badge: "Same week",
    image:
      "https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: false,
    promotion: false,
    freeTrial: true,
    isNew: true,
    likes: 236,
  },
  {
    name: "Glow Beauty Studio",
    provider: "Glow Beauty & Wellness",
    category: "Facial care",
    group: "Beauty & wellness",
    offer: "20% off first visit",
    price: 68,
    unit: "treatment",
    distance: 1.8,
    badge: "20% OFF",
    image:
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: true,
    freeTrial: false,
    isNew: false,
    likes: 356,
  },
  {
    name: "Lumiere Aesthetic Clinic",
    provider: "Lumiere Medical Aesthetics",
    category: "Skin care",
    group: "Beauty & wellness",
    offer: "Free consult",
    price: 120,
    unit: "visit",
    distance: 2.3,
    badge: "Consultation",
    image:
      "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: false,
    promotion: false,
    freeTrial: true,
    isNew: false,
    likes: 297,
  },
  {
    name: "Calm Body Massage",
    provider: "Calm Body Wellness",
    category: "Massage therapy",
    group: "Beauty & wellness",
    offer: "Weekday 60 min",
    price: 72,
    unit: "session",
    distance: 0.9,
    badge: "10% OFF",
    image:
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: true,
    freeTrial: false,
    isNew: false,
    likes: 315,
  },
  {
    name: "BrightSmile Dental",
    provider: "BrightSmile Family Dental",
    category: "Family dental",
    group: "Health",
    offer: "Check-up package",
    price: 80,
    unit: "visit",
    distance: 1.4,
    badge: "New patient",
    image:
      "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: false,
    freeTrial: true,
    isNew: true,
    likes: 261,
  },
  {
    name: "Orchard Dental Studio",
    provider: "Orchard Dental Studio",
    category: "Hygiene & whitening",
    group: "Health",
    offer: "Smile refresh",
    price: 95,
    unit: "visit",
    distance: 2.1,
    badge: "Smile refresh",
    image:
      "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: false,
    weekend: false,
    promotion: true,
    freeTrial: false,
    isNew: false,
    likes: 229,
  },
  {
    name: "Little Teeth Clinic",
    provider: "Little Teeth Family Dentistry",
    category: "Kids dental",
    group: "Health",
    offer: "First check-up",
    price: 68,
    unit: "visit",
    distance: 0.9,
    badge: "Kids welcome",
    image:
      "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=520&h=390&q=85",
    openNow: true,
    weekend: true,
    promotion: false,
    freeTrial: true,
    isNew: false,
    likes: 338,
  },
]

export function parseSectionGroup(sectionTitle: string): string {
  return sectionGroupLookup[sectionTitle] ?? "All"
}

export function isDiscountBadge(badge: string): boolean {
  return /^(?:[0-9]+%|\$[0-9]+)\s*OFF\b/i.test(badge.trim())
}
